repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=2000']
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: [ --autofix, --no-sort-keys ]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.2
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [ --fix, --exit-non-zero-on-fix ]
      - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: [-L, "ans,fpr"]  # Allow extra words
        additional_dependencies:
          - tomli
        exclude: ^(datasets/sports-players/.*\.(txt|json))$
  - repo: local
    hooks:
    - id: pyright
      name: pyright
      stages: [commit]
      types: [python]
      entry: pyright
      language: system
      pass_filenames: false
      always_run: true
